#! /bin/zsh

bspc rule -r "*"
############
# Autostarts
############
# compositor is needed
pkill picom 
picom &
# background setter
pkill tapet
tapet -d &
# hide mouspointer when not used
pkill unclutter
unclutter &

. .zshrc
# set keybinding daemon
pkill sxhkd
sxhkd -m 1 &
# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config automatic_scheme alternate
bspc config border_width 2
bspc config focused_border_color "#88c0d0"

# No gaps, that's just wasted space
bspc config window_gap 2
bspc config history_aware_focus true

# Ratio of main window to stack
bspc config split_ratio 0.52

# Monocle also without borders
bspc config borderless_monocle true
bspc config gapless_monocle true

#swallow terminals
pgrep bspswallow || ~/bin/bspswallow &

# launch new bar
pkill bspwmbar
#bspwmbar &
~/.config/polybar/launch.sh

